package com.example.rustorescreen.domain.domainModel

enum class AppCategory {
    APP, GAME, PRODUCTIVITY, SOCIAL, EDUCATION, ENTERTAINMENT, MUSIC, VIDEO, PHOTOGRAPHY, HEALTH, SPORTS,
    NEWS, BOOKS, BUSINESS, FINANCE, LIFESTYLE, TRAVEL, MAPS, FOOD, SHOPPING, UTILITIES
}